fix: dont show upcoming occurrences in event card when there is none
City-of-Helsinki/palvelutarjotin-ui pull request #156
Opened 2021-09-17 13:53 UTC by Sartonon

## Description :sparkles:

- Dont show upcoming occurrences in event card when there is none
- Show "No upcoming occurrences" text when event has no more upcoming occurrences

## Issues :bug:

### Closes :no_good_woman:

**[PT-1208](https://helsinkisolutionoffice.atlassian.net/browse/PT-1208):**
**[PT-1164](https://helsinkisolutionoffice.atlassian.net/browse/PT-1164):**

### Related :handshake:

## Testing :alembic:

### Automated tests :gear:️

### Manual testing :construction_worker_man:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2021-09-20 07:04 UTC, Sartonon commented on src/domain/events/EventsPage.tsx
> +  // getEventsThatHaveUpcomingOccurrence(eventsData);
I still need to delete this commented line

2021-09-21 07:01 UTC, nikomakela requested changes
Tested locally:

![image](https://user-images.githubusercontent.com/389204/134125147-12cc8731-2171-48aa-92f1-2444e3849368.png)

It says "no upcoming occurrences", but still renders the "other event times" -button.

Response from graphQl API:
```
pEvent: {id: "UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjM3", nextOccurrenceDatetime: null,…}
id: "UGFsdmVsdXRhcmpvdGluRXZlbnROb2RlOjM3"
lastOccurrenceDatetime: "2021-04-30T22:30:00+00:00"
nextOccurrenceDatetime: null
```

The code checks 

```
const hasMultipleOccurrences = nextOccurrenceTime !== lastOccurrenceTime;
```

but the lastOccurrenceTime is given, even when it's in past.

The variable name should be changed and the button should be shown only when the last occurrence is in future.

2021-09-21 07:21 UTC, nikomakela commented
needless imports reported by automation tools could also be resolved when a requested change is full filled

2021-09-21 08:47 UTC, nikomakela approved these changes

2021-09-21 08:48 UTC, merged