feat: unit place selector uses schoolsAndKindergartens query
City-of-Helsinki/palvelutarjotin-ui pull request #173
Opened 2021-11-11 07:33 UTC by nikomakela

API returns all the units (1000+ pcs) all at once from schoolsAndKindergartens graphql query. The Enrolment form autosuggest field for unit selection should be able to filter the list of units with an input value.

PT-1314.

2021-11-11 10:21 UTC, nikomakela commented
- [ ] Tests are still missing

2021-11-11 11:44 UTC, Sartonon requested changes
Otherwise looks good but some code should be refactored out of PlaceText component :)

2021-11-11 11:44 UTC, Sartonon commented on src/domain/place/placeText/PlaceText.tsx
> +  return <>{text || errorText}</>;
This feels unnecessarily complicated. Maybe could get rid of `!text` because it is redundant with this code.

2021-11-11 11:44 UTC, Sartonon commented on src/domain/place/placeText/PlaceText.tsx
> +  return <>{text || errorText}</>;
I also think that `t('placeText.noPlaceFoundError')` shouldn't be in this component but rather provided as errorText prop

2021-11-11 11:44 UTC, Sartonon commented on src/domain/place/placeText/PlaceText.tsx
> +  return <>{text || errorText}</>;
Because this is general reusable component and text "Paikka on valittu..." is specific to UnitPlaceSelector.

2021-11-15 15:09 UTC, nikomakela commented
The acceptance tests are failing again 😞 . I'm quite sure it's related to a Linkedevent cache.

2021-11-18 11:57 UTC, merged